### ISSUE TITLE
Add schema for a data resource reference

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ExecutionBroker#121]
A data resource place holder that can be defined in the metadata for an executable, and replaced by a real data resource when the user selects the data they want to use.
Basic properties such as the name, the IVOA data product type (from ObsCore)
```
resources:
  data:
    - name: input data
      ivoa:
        obscore:
          dataproduct_type: spectra
```     
This acts as a hint for the UI to guide the user to select the right type of data.
It can also be referenced by compute resource volumes to specify the mount point.
