### ISSUE TITLE
Replace individual max and min values with pairs

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ExecutionBroker#47]
The current document has lots of `maxxxxx` and `minxxxx` properties, using the property names to link them together.
```
resources:
  compute:
  - name: "compute-001"
    type: "https://www.purl.org/ivoa.net/resource-types/generic-compute"
    spec:
      mincores: 8
      maxcores: 16
      minmemory: 16
      maxmemory: 32 
```

This means each class object has lots of top level `minxxx` and `maxxxx` properties associated with it, cluttering up the class interface.

It is better to define maximum and minimum properties as a re-useable element that contains the `min` and `max` values as a pair.

```
resources:
  compute:
  - name: "compute-001"
    type: "https://www.purl.org/ivoa.net/resource-types/generic-compute"
    spec:
      cores:
        min: 8
        max: 16
      memory:
        min: 16
        max: 32 
``` 

It cleans up the class interfaces and enables us to automate some validation that checks that the max value is always greater than the min value.
