### ISSUE TITLE
Both ExecBroker and ExecWorker use 'options'

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ExecutionBroker#69]
Both web services are self-describing, using the `options` pattern to describe what the client can do.

ExecutionBroker broker response
```
offers:
- ident: 001
  status: "OFFERED"
  ....
  options:
  - path: "status"
    values: ["ACCEPTED, REJECTED"]
....
```
    
ExecutionBroker individual offer
```
offer:
- ident: 001
  status: "OFFERED"
  ....
  options:
  - path: "status"
    values: ["ACCEPTED, REJECTED"]
....
```

ExecutionWorker individual session 
```
session:
- ident: 361
  status: "RUNNING"
  ....
  options:
  - path: "status"
    values: ["CANCELLED"]
....
```
