### ISSUE TITLE
Add support for Docker Compose 

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ExecutionBroker#72]
Adding Docker Compose executables would provide support for multi-container deployments (e.g. an application and database sidecar).

```
executable:
- type: "https://..../docker-compose"
  spec:
    file: "https://github.com/.../compose.yaml"
    ....
```
The compose file would contain details of the application and database sidecar, along with the internal filesystem and network connecting them. This would provide access to all of the Docker Compose tools for orchestrating inter-container filesystem and networking, without us having to re-invent any wheels.

Platforms that don't support Docker Compose executables simply reply `NO`.
