### ISSUE TITLE
List of locations

### ISSUE THREAD

**Issue by Zarquan** [ivoa-std/ExecutionBroker#85]
Change the model for executables like Docker containers and Jupyter notebooks to include a list of multiple source locations, and a file size and checksum to verify it.

```
executable:
  name: My Jupyter notebook
  type: urn:jupyter-notebook-0.1
  notebook:
    source:
      type: urn:file-download
      filename: 02_dmhh.ipynb
      filepath: "${sesionhome}"
      source:
        - https://www.github.com/....
        - https://www.gitlab.com/....
      filesize:
        value: 14270
        units: B
      checksums:
        - algorithm: md5sum
          value: 857480ff982d88530f876b95046fa601
```
